### ISSUE TITLE
Keep getting logged out of Tabnine extenstion

### ISSUE THREAD

**Issue by mpreston88** [codota/tabnine-vscode#1570]
I am using the Tabnine VSCode extension on WSL(Ubuntu) and I keep getting logged out while trying to use it. 

Here is the output from the VSCode logs 
```
08:42:40 GMT-0400 (Eastern Daylight Time) [WARN]: BinaryTimeoutError: Binary request timed out. {"State":{}} 
08:42:40 GMT-0400 (Eastern Daylight Time) [ERROR]: failed to handle event. command: get_user, error: "state is undefined" 
```

I have simply tried to log back in with no luck. 
I have removed the extension and deleted the cache in both the Windows and Linux directories to no avail. 

gz#39935<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/39935'>Zendesk ticket #39935</a>)</i>

**Comment by rickhg12hs** [comment]
As an early adopter, I was given a TabNine Pro access token and have been using it since 2019.  Now I'm logged out too.

Maybe my days with TabNine are over.

**Comment by TzufTabnine** [comment]
The issue has been resolved. Sorry for the inconvenience.

**Comment by mpreston88** [comment]
@TzufTabnine I am still having this issue today. Is there something else I need to do on my end?

**Comment by TzufTabnine** [comment]
@mpreston88 Please send us a screen recording and logs of the current issue.

**Comment by mpreston88** [comment]
https://github.com/user-attachments/assets/debe6478-ce5d-4ad9-abaf-4ecf2080d2f4

Here is a screen grab, it is pretty intermittent so it was hard to get a good capture. I'd rather not post the whole log file but you can see at the end of the capture the same logs from above.

**Comment by TzufTabnine** [comment]
Please send us the logs (https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Logs-on-VSCode) to support@tabnine.com

**Comment by yjqiang** [comment]
艹你妈的，一分钟重新登录十次，nmd 还要 log，log 你自己还原不了？
