### ISSUE TITLE
TabNine 3.2.6 doesn't work on my installation

### ISSUE THREAD

**Issue by fungiboletus** [codota/tabnine-vscode#323]
- OS version: Ubuntu 18.04.5 LTS 5.4.72-microsoft-standard-WSL2
- Editor version: 1.52.1
- Programming language: all
- TabNine extension version: 3.2.6

The TabNine configuration page is empty. There is nothing on the logs.

Everything works if I downgrade to version 3.2.4 from last week.

**Comment by dimacodota** [comment]
hi @fungiboletus, when running the 3.2.6 version, do you see `tabnine` in the status bar? 
can you please share your tabnine_config.json file? 

for Linux it should be located at `
$XDG_CONFIG_HOME or $HOME/.config/TabNine
/home/alice/.config/Tabnine`

for windows `{FOLDERID_RoamingAppData}\TabNine`

**Comment by fungiboletus** [comment]
Yes using tabnine 3.2.6, the tabnine button is in the status bar.

This is my `tabnine_config.js` file:

```json
{
  "version": "3.1.14",
  "hide_promotional_message": false,
  "beta_enabled": "No",
  "ignore_all_lsp": false,
  "creation_time": "2020-11-10T12:45:39.723816Z",
  "guuid": null,
  "semantic_status": {},
  "enable_telemetry": false,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": false,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": null,
  "multiline_suggestions": null,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 30,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": null
}
```

**Comment by MariusVB** [comment]
Same issue here. Pop-os 20.10 (Ubuntu derivate).
config looks like this
`{
  "version": "3.2.34",
  "hide_promotional_message": false,
  "beta_enabled": "No",
  "ignore_all_lsp": false,
  "creation_time": "2020-12-02T19:28:15.869203190Z",
  "guuid": "5d649545c591b57c27fee8787ab17964bcdd941aacf2104ba58624c294519b5c",
  "semantic_status": {},
  "enable_telemetry": true,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": false,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": null,
  "multiline_suggestions": null,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 32,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": null
}⏎                     `

**Comment by dimacodota** [comment]
Hi @MariusVB, can you please share a screen recording of the issue? Thanks

**Comment by MariusVB** [comment]
https://user-images.githubusercontent.com/24921111/107225513-2c9ac800-6a19-11eb-9065-77e91db96a2e.mp4

**Comment by dimacodota** [comment]
@MariusVB - can you please close all your tabnine instances and reload your ide (i suspect that you have some zombie process running)?

**Comment by MariusVB** [comment]
Restarted my computer but didn't work. Downgraded to 3.2.3 and it works now.

**Comment by dimacodota** [comment]
@MariusVB - thanks for the debug session! this is very helpful.  can you please reinstall 3.2.6 and send us the vscode extension log (Help -> Toggle developer tools)?

**Comment by MariusVB** [comment]
Really weird - reinstalled 3.2.6 for the 5th time and now it works..

**Comment by dimacodota** [comment]
> Really weird - reinstalled 3.2.6 for the 5th time and now it works..

oh, that strange...

**Comment by rapritchard** [comment]
I'm also getting this issue, and I have reinstalled the extension 5 times.

Here is my config file:

```json
{
  "version": "3.3.48",
  "hide_promotional_message": false,
  "beta_enabled": "No",
  "ignore_all_lsp": false,
  "creation_time": "2021-02-08T17:46:18.121359600Z",
  "guuid": "5176da141f974466049d2faeda4b4a4185b9a75b03d0b20fc50428dc24691a1f",
  "semantic_status": {},
  "enable_telemetry": true,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 5,
  "multiline_suggestions": null,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 40,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": null
}
```

And here is a screenshot of using the developer tools and trying to access the Tabnine page which is empty:

![image](https://user-images.githubusercontent.com/32645551/107345856-ee0a1980-6abb-11eb-95db-8fb04e8a9845.png)

**Comment by dimacodota** [comment]
@rapritchard Thanks, can you please paste the log?

**Comment by rapritchard** [comment]
```
Some messages have been moved to the Issues panel.
workbench.desktop.main.js:60 [Extension Host] (node:19312) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
b @ workbench.desktop.main.js:60
$logExtensionHostMessage @ workbench.desktop.main.js:1566
_doInvokeHandler @ workbench.desktop.main.js:1566
_invokeHandler @ workbench.desktop.main.js:1566
_receiveRequest @ workbench.desktop.main.js:1566
_receiveOneMessage @ workbench.desktop.main.js:1566
(anonymous) @ workbench.desktop.main.js:1566
fire @ workbench.desktop.main.js:55
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:55
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
I @ workbench.desktop.main.js:2653
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
workbench.desktop.main.js:60 [Extension Host] resolved immediately
workbench.desktop.main.js:60 [Extension Host] "live-sass-compiler" is now activated! Go and debug :P 
workbench.desktop.main.js:60 [Extension Host] Error: Could not get enabled capabilities    at Object.getCapabilities (c:\Users\Reecep\.vscode\extensions\tabnine.tabnine-vscode-3.2.6\out\binary\requests\requests.js:42:19)    at runNextTicks (internal/process/task_queues.js:62:5)    at processTimers (internal/timers.js:489:9)
b @ workbench.desktop.main.js:60
$logExtensionHostMessage @ workbench.desktop.main.js:1566
_doInvokeHandler @ workbench.desktop.main.js:1566
_invokeHandler @ workbench.desktop.main.js:1566
_receiveRequest @ workbench.desktop.main.js:1566
_receiveOneMessage @ workbench.desktop.main.js:1566
(anonymous) @ workbench.desktop.main.js:1566
fire @ workbench.desktop.main.js:55
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:55
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
I @ workbench.desktop.main.js:2653
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186

```

**Comment by fungiboletus** [comment]
> @fungiboletus - can you please try to reinstall 3.2.6 and share here the vscode extension log?

Strange too. It works now but I can't really explain why.

**Comment by dimacodota** [comment]
I have released version 3.2.7, please update it and report if you have any issue. Thanks

**Comment by dimacodota** [comment]
> I have released version 3.2.7, please update it and report if you have any issue. Thanks

@rapritchard

**Comment by rapritchard** [comment]
@dimacodota I'm still unable to use the extension after updating to 3.2.7. Same error in the console too. 

![image](https://user-images.githubusercontent.com/32645551/107383395-da28dc80-6ae8-11eb-9022-0ce49052766f.png)

**Comment by dimacodota** [comment]
@rapritchard - I see that you have an "UNRESPONSIVE extension host" warning, can you please share the `.cpuprofile` file?

**Comment by rapritchard** [comment]
@dimacodota 

[.cpuprofile file](https://drive.google.com/file/d/1_dQc4fbipWzbfQs78677DLsjc3iRvOHA/view?usp=sharing)

**Comment by dimacodota** [comment]
@rapritchard, can you please check if the old (3.2.5) version of Tabnine works for you?

**Comment by dimacodota** [comment]
> @rapritchard, can you please check if the old (3.2.5) version of Tabnine works for you?

one more thing, can you please share a screenshot of the `binaries` directory located under the tabnine extension installation directory? 
vscode extensions lcation should be `%USERPROFILE%\.vscode\extensions` for windows

**Comment by rapritchard** [comment]
I get the same error in the developer console in version 3.2.5. I'm starting to think it may be my work machine messing up, so I need to try installing it on my personal machine to confirm.

And a screenshot of my binaries in the latest version.

![image](https://user-images.githubusercontent.com/32645551/107500070-a6ec5900-6b8d-11eb-8cb1-45fbeb625f35.png)

**Comment by dimacodota** [comment]
@rapritchard - I've made some changes related to your CPU log (thanks a lot for that 🙏 ) can you please try to install the vsix attached to [this alpha release](https://github.com/codota/tabnine-vscode/releases/tag/v3.2.7-alpha.20210210165451) ?

**Comment by rapritchard** [comment]
Tried to install that alpha release and ran into an error with the installer.
![image](https://user-images.githubusercontent.com/32645551/107623404-2e4ed080-6c51-11eb-9afa-4be4bc4c6a65.png)

Here's the log:

```
11/02/2021 10:08:07 - Microsoft VSIX Installer
11/02/2021 10:08:07 - -------------------------------------------
11/02/2021 10:08:07 - vsixinstaller.exe version:
11/02/2021 10:08:07 - 16.7.3069
11/02/2021 10:08:07 - -------------------------------------------
11/02/2021 10:08:07 - Command line parameters:
11/02/2021 10:08:07 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Reecep\Downloads\tabnine-vscode.vsix
11/02/2021 10:08:07 - -------------------------------------------
11/02/2021 10:08:07 - Microsoft VSIX Installer
11/02/2021 10:08:07 - -------------------------------------------
11/02/2021 10:08:08 - Skipping product Microsoft.VisualStudio.Product.BuildTools (ea408851) since it does not support extensions
11/02/2021 10:08:08 - Initializing Install...
11/02/2021 10:08:08 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Metadata' has attribute 'DisplayName' with value 'Tabnine Autocomplete AI: JavaScript, Python, TypeScript, PHP, Go, Java, Ruby, C/C++, HTML/CSS, C#, Rust, SQL, Bash, Kotlin, React' whose length is greater than maximum value of 100.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyString(String value, ErrorInfo info, Boolean isRequired, Int32 maxLength, String defaultValue)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by dimacodota** [comment]
@rapritchard - can you please install it via the vscode extensions tab?

<img width="705" alt="Screen Shot 2021-02-11 at 14 38 51" src="https://user-images.githubusercontent.com/60742964/107638028-b051f000-6c77-11eb-8032-c2dcfc91fbd5.png">


Thanks

**Comment by rapritchard** [comment]
Hi @dimacodota

Sorry for the late reply, the alpha version you asked me to install seems to work now, but this only seem to happen after my company updated my machine.

Thanks :)
