### ISSUE TITLE
`tabnine.disable_line_regex` does not work

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [codota/tabnine-vscode#831]
**Please complete the following information:**

- OS version: Ubuntu
```
Linux CADENZA-JOSHUA 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
- Editor version 1.67.0
- Programming language: tsx
- TabNine extension version: 3.5.45

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

^^^ I followed these instructions, but do not see the logs on the "Tabnine Hub" page.

**Editor console logs:**

Help -> Toggle Developer Tools

Logs matching tabnine:
```
CRITI Extension 'TabNine.tabnine-vscode CANNOT USE these API proposals 'inlineCompletions'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
log.ts:313   ERR [Extension Host] validating /home/joshua/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.6/x86_64-unknown-linux-musl/TabNine timeout
console.ts:137 [Extension Host] validating /home/joshua/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.6/x86_64-unknown-linux-musl/TabNine timeout
E @ console.ts:137
```

**Issue Details:**

### What I Did
I followed the instructions in the [Settings configuration description](https://github.com/codota/tabnine-vscode/blob/e3ba66bfa00b98fa0ecc081f75691b731088f28b/package.json#L297) and set `tabnine.disable_line_regex` to an array including `"require"` like so:
```json
    "tabnine.experimentalAutoImports": true,
    "tabnine.disable_line_regex": ["require"]
```

### What I Expected
I expected Tabnine to be disabled when I'm typing in a line that included the word `require` (as the description for that setting says).

### What Happened
When typing in the following line, Tabnine still showed tab-completable suggestions (suggested `document` as an auto complete):
```
const require = d
```

I tried other regexes that also didn't work.

    

gz#14033

**Comment by talcodota** [comment]
We are currently working on a fix.
Thanks for reporting.

**Comment by talcodota** [comment]
Fixed on tabnine vscode version 3.5.47.
Note you should now use camelcase naming convention:
`disableLineRegex`

**Comment by JoshuaCWebDeveloper** [comment]
@talcodota Hmm.... did anything else change as well? I updated to 3.5.47 (updated settings, restarted VSCode), but with the following settings, I still get the same result as above:
```
    "tabnine.experimentalAutoImports": true,
    "tabnine.disableLineRegex": ["require"]
```

**Comment by talcodota** [comment]
@JoshuaCWebDeveloper are the suggestions coming from tabnine? 
can you please share a screenshot of the suggestions?

**Comment by JoshuaCWebDeveloper** [comment]
Here you go:
https://user-images.githubusercontent.com/6536826/168966109-2c54241e-2d9e-4e98-86c3-e93545407b30.mp4

**Comment by talcodota** [comment]
@JoshuaCWebDeveloper thank you for that!
We release a fix in v3.5.48.
Please let me know if it's working for you now.
